default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: jchris
  password:

development:
  <<: *default
  database: reverb_development

test: &TEST
  <<: *default
  database: reverb_test

production:
  <<: *default
  database: reverb_production

