# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb275142bea3c62c9bb1d1da97c5e261b41d805bd64a00d24e46999eae0f5e8968ea0bf750812d0c23503f9928f6ab5e13f7cc6858eda42df7a1dd7c4891f28

test:
  secret_key_base: 38219daf277cfa557e3c483d5fd81e6de8b0e546aec95f98dc3a2a2072d4fee978a9f74aa58dd139cca4bf7af30e0ba73458dc3e4c333f2e46d08b329a1dd85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
